import { StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  bgImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  container: {
    padding: 16,
    alignItems: 'stretch',
    width: '100%',
    paddingBottom: 100, // Space for floating button
  },
  welcomeSection: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  logo: {
    width: 80,
    height: 80,
    marginBottom: 8,
  },
  welcomeText: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  tipBox: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 8,
    marginTop: 8,
    marginBottom: 2,
    alignSelf: 'stretch',
  },
  tipText: {
    fontSize: 15,
    textAlign: 'center',
  },
  quickColumn: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 16,
  },
  panicButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#B00020',
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginBottom: 16,
    width: '95%',
    alignSelf: 'center',
    elevation: 4,
    shadowColor: '#B00020',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  panicButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  quickButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7B3FA0',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginBottom: 12,
    width: '95%',
    alignSelf: 'center',
    elevation: 2,
  },
  quickButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  statusCard: {
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    marginHorizontal: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    width: '100%',
    alignSelf: 'center',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 16,
    fontWeight: '500',
    flex: 1,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 8,
  },
  addressContainer: {
    marginTop: 8,
    padding: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(123, 63, 160, 0.1)',
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  addressText: {
    fontSize: 14,
    marginLeft: 8,
    marginRight: 8,
    flex: 1,
  },
  addressHint: {
    fontSize: 12,
    opacity: 0.7,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  mapContainer: {
    width: '100%',
    height: 300,
    borderRadius: 12,
    marginTop: 12,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#f0f0f0',
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  locationPreview: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  locationText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  addressText: {
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.7,
  },
  mapLoading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapLoadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
  },
  mapError: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  mapErrorText: {
    marginTop: 12,
    fontSize: 16,
    color: '#B00020',
    textAlign: 'center',
  },
  mapDebug: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255,255,255,0.9)',
    padding: 8,
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  mapLoading: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  mapLoadingText: {
    marginTop: 8,
    color: '#333',
    fontSize: 14,
  },
  mapError: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 230, 230, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    zIndex: 3,
  },
  mapErrorText: {
    marginTop: 8,
    color: '#B00020',
    textAlign: 'center',
    fontSize: 14,
  },
  marker: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerRing: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(123, 63, 160, 0.3)',
  },
  markerDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#7B3FA0',
    borderWidth: 2,
    borderColor: 'white',
  },
  activityCard: {
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    marginHorizontal: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    width: '100%',
    alignSelf: 'center',
  },
  activityTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  activityIcon: {
    marginRight: 12,
  },
  activityText: {
    fontSize: 16,
    flex: 1,
  },
  activityTime: {
    fontSize: 12,
    opacity: 0.6,
  },
  checklistCard: {
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    width: '100%',
    alignSelf: 'center',
  },
  checklistTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    marginBottom: 4,
  },
  checklistText: {
    fontSize: 16,
    marginLeft: 12,
    flex: 1,
  },
  toast: {
    position: 'absolute',
    top: 50,
    left: 20,
    right: 20,
    borderRadius: 16,
    padding: 12,
    zIndex: 10,
    alignItems: 'center',
  },
  toastText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tipCycleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(123, 63, 160, 0.1)',
  },
  tipCycleText: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  tipCategorySelector: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  tipCategoryButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginHorizontal: 2,
    borderRadius: 12,
    elevation: 1,
  },
  tipCategoryButtonText: {
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 4,
  },
  tipCategoryIcon: {
    fontSize: 16,
  },
  tipCategoryCount: {
    fontSize: 8,
    opacity: 0.8,
    marginTop: 2,
  },
  tipProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  tipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 2,
  },
  tipSubtext: {
    fontSize: 12,
    textAlign: 'center',
    marginTop: 4,
    opacity: 0.7,
  },
  tipContainer: {
    marginBottom: 8,
  },
  tipCategoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 8,
    elevation: 2,
  },
  tipCategoryText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  tipCategoriesContainer: {
    borderRadius: 12,
    marginBottom: 8,
    elevation: 2,
    overflow: 'hidden',
  },
  tipCategoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tipCategoryItemText: {
    fontSize: 15,
    fontWeight: '500',
  },
  tipFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  tipCounter: {
    fontSize: 12,
    fontWeight: 'bold',
    opacity: 0.8,
  },
  panicSubText: {
    color: '#fff',
    fontSize: 12,
    opacity: 0.8,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  quickActionGridItem: {
    width: '48%',
    aspectRatio: 1.4,
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  quickActionGridItemLong: {
    width: '100%',
    height: 80,
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  quickActionGridText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 6,
    textAlign: 'center',
  },
  quickButtonSubText: {
    color: '#fff',
    fontSize: 12,
    opacity: 0.8,
  },
  // Missing styles that are referenced in HomeScreen
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    padding: 16,
    marginHorizontal: 4,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
    textAlign: 'center',
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
  },

  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 8,
    marginHorizontal: 16,
  },
  floatingButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    zIndex: 1000,
  },
  floatingButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#B00020',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#B00020',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
});
